# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '20190108_WebSocket_Starscream' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'Starscream', '~> 3.0.2'

  # Pods for 20190108_WebSocket_Starscream

end
