# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '20190425_webSocketChatroom' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Starscream', '~> 3.0.2'
    pod 'SwiftyJSON'
  # Pods for 20190425_webSocketChatroom

end
